from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
import gradio as gr

# Suppress warnings generated by the code
def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM Configuration
def get_llm():
    model_id = 'mistralai/mixtral-8x7b-instruct-v01'  # Use the model that fits your requirement
    parameters = {
        GenParams.DECODING_METHOD: "greedy",  # Use greedy decoding method for simplicity
        GenParams.MAX_NEW_TOKENS: 500,       # Max number of tokens generated
        GenParams.MIN_NEW_TOKENS: 1,         # Min number of tokens generated
        GenParams.TEMPERATURE: 0.5,          # Lower temperature for determinism
        GenParams.TOP_P: 0.95,               # Top-p sampling
        GenParams.TOP_K: 50,                 # Top-k sampling
        GenParams.REPETITION_PENALTY: 1.05,  # Repetition penalty
    }
    
    project_id = "9824efd0-0c60-43e5-beae-aef520f88ad7"  # Set your Watsonx project ID
    api_key = "Vbphrm0alv5xGKEAnjKyPN7CKzJaFvBMfYj0vXylaqWt"  # Replace with your new API key
    
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://eu-de.ml.cloud.ibm.com",  # Your specific Watsonx URL (adjust if needed)
        project_id=project_id,
        params=parameters,
        apikey=api_key,  # Pass the API key here
    )
    return watsonx_llm

## Document loader
def document_loader(file):
    loader = PyPDFLoader(file.name)  # Use PyPDFLoader to load the PDF file
    loaded_document = loader.load()  # Load the content of the PDF
    return loaded_document

## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,        # Split the document into chunks of 500 tokens
        chunk_overlap=100,     # Overlap between chunks for context preservation
        length_function=len,   # Use the length of the text as a metric
    )
    chunks = text_splitter.split_documents(data)  # Split the document into chunks
    return chunks

## Embedding model
def watsonx_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 512,  # Truncate input tokens for embeddings
    }
    watsonx_embedding = WatsonxEmbeddings(
        model_id="ibm/slate-30m-english-rtl",  # Your embedding model ID
        url="https://eu-de.ml.cloud.ibm.com",  # Watsonx URL
        project_id="9824efd0-0c60-43e5-beae-aef520f88ad7",  # Your project ID
        params=embed_params,
        apikey=api_key  # Pass the API key here as well
    )
    return watsonx_embedding

## Vector DB
def vector_database(chunks):
    embedding_model = watsonx_embedding()  # Get the embedding model
    vectordb = Chroma.from_documents(chunks, embedding_model)  # Create a vector DB using Chroma
    return vectordb

## Retriever
def retriever(file):
    splits = document_loader(file)  # Load documents
    chunks = text_splitter(splits)  # Split documents into chunks
    vectordb = vector_database(chunks)  # Create a vector database
    retriever = vectordb.as_retriever()  # Create retriever from vector database
    return retriever

## QA Chain
def retriever_qa(file, query):
    llm = get_llm()  # Initialize LLM
    retriever_obj = retriever(file)  # Initialize retriever
    qa = RetrievalQA.from_chain_type(
        llm=llm, 
        chain_type="stuff",  # You can change the chain type based on requirements
        retriever=retriever_obj, 
        return_source_documents=True  # Return the source documents as well
    )
    response = qa.invoke(query)  # Process the query with the QA chain
    return response['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,  # Function to call for the interface
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag-and-drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")  # Input query for question
    ],
    outputs=gr.Textbox(label="Answer", lines=5),  # Output response in a text box
    title="RAG Assistant - Document Question Answering",  # Title of the app
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="127.0.0.1", server_port=7860)  # Launch the app locally
